export const Sector = {
  GAZA: "gaza",
  LEBANON: "lebanon",
} as const;
export type Sector = (typeof Sector)[keyof typeof Sector];

export const LaunchingOrganization = {
  HEZBOLLAH: "hezbollah",
  HAMAS: "hamas",
} as const;
export type LaunchingOrganization =
  (typeof LaunchingOrganization)[keyof typeof LaunchingOrganization];

/** Where the event physically resolved: the drone was brought down, or it struck something */
export const EventLocationType = {
  FALL: "fall",
  INTERCEPT: "intercept",
} as const;
export type EventLocationType = (typeof EventLocationType)[keyof typeof EventLocationType];

export const EventStatus = {
  INTERCEPTED: "intercepted",
  FELL_IN_OPEN_FIELD: "fell_in_open_field",
  HIT_TARGET: "hit_target",
  IN_AIR: "in_air",
} as const;
export type EventStatus = (typeof EventStatus)[keyof typeof EventStatus];

// --- Reference entities, mirroring the ERD (DRONE_TYPE, DRONE, LAUNCHER_TYPE, LAUNCHER, INTERCEPTOR_TYPE) ---

export interface DroneType {
  id: number;
  name: string;
}

export interface Drone {
  id: number;
  droneType: DroneType;
  heading: number;
  velocity: number;
}

export interface LauncherType {
  id: number;
  name: string;
  reloadTimeS: number;
}

export interface Launcher {
  id: number;
  launcherType: LauncherType;
  longitude: number;
  latitude: number;
  asl: number;
  agl: number;
  amount: number;
  active: boolean;
}

export interface InterceptorType {
  id: number;
  name: string;
  rangeM: number;
}

export const droneTypesMock: DroneType[] = [
  { id: 1, name: "Shahed-136" },
  { id: 2, name: "Zamzam-1" },
  { id: 3, name: "Ababil-2" },
  { id: 4, name: "Qasef-2K" },
];

export const launcherTypesMock: LauncherType[] = [
  { id: 1, name: "Fixed Rail Launcher", reloadTimeS: 45 },
  { id: 2, name: "Mobile Multi-Rail Launcher", reloadTimeS: 30 },
];

export const launchersMock: Launcher[] = [
  {
    id: 1,
    launcherType: launcherTypesMock[0],
    longitude: 34.465,
    latitude: 31.42,
    asl: 45,
    agl: 3,
    amount: 12,
    active: true,
  },
  {
    id: 2,
    launcherType: launcherTypesMock[1],
    longitude: 34.39,
    latitude: 31.47,
    asl: 60,
    agl: 3,
    amount: 8,
    active: true,
  },
  {
    id: 3,
    launcherType: launcherTypesMock[0],
    longitude: 34.51,
    latitude: 31.385,
    asl: 30,
    agl: 3,
    amount: 10,
    active: true,
  },
  {
    id: 4,
    launcherType: launcherTypesMock[1],
    longitude: 35.26,
    latitude: 33.11,
    asl: 520,
    agl: 4,
    amount: 14,
    active: true,
  },
  {
    id: 5,
    launcherType: launcherTypesMock[0],
    longitude: 35.43,
    latitude: 33.22,
    asl: 610,
    agl: 4,
    amount: 9,
    active: true,
  },
];

export const interceptorTypesMock: InterceptorType[] = [
  { id: 1, name: "Tamir", rangeM: 70000 },
  { id: 2, name: "Stunner", rangeM: 300000 },
  { id: 3, name: "Iron Beam", rangeM: 10000 },
  { id: 4, name: "Barak-8", rangeM: 150000 },
  { id: 5, name: "C-Dome", rangeM: 70000 },
];

export const dronesMock: Drone[] = [
  { id: 1, droneType: droneTypesMock[0], heading: 0, velocity: 20 },
  { id: 2, droneType: droneTypesMock[1], heading: 23, velocity: 23 },
  { id: 3, droneType: droneTypesMock[2], heading: 46, velocity: 26 },
  { id: 4, droneType: droneTypesMock[3], heading: 69, velocity: 29 },
  { id: 5, droneType: droneTypesMock[0], heading: 92, velocity: 32 },
  { id: 6, droneType: droneTypesMock[1], heading: 115, velocity: 35 },
  { id: 7, droneType: droneTypesMock[2], heading: 138, velocity: 38 },
  { id: 8, droneType: droneTypesMock[3], heading: 161, velocity: 41 },
  { id: 9, droneType: droneTypesMock[0], heading: 184, velocity: 20 },
  { id: 10, droneType: droneTypesMock[1], heading: 207, velocity: 23 },
  { id: 11, droneType: droneTypesMock[2], heading: 230, velocity: 26 },
  { id: 12, droneType: droneTypesMock[3], heading: 253, velocity: 29 },
  { id: 13, droneType: droneTypesMock[0], heading: 276, velocity: 32 },
  { id: 14, droneType: droneTypesMock[1], heading: 299, velocity: 35 },
  { id: 15, droneType: droneTypesMock[2], heading: 322, velocity: 38 },
  { id: 16, droneType: droneTypesMock[3], heading: 345, velocity: 41 },
  { id: 17, droneType: droneTypesMock[0], heading: 8, velocity: 20 },
  { id: 18, droneType: droneTypesMock[1], heading: 31, velocity: 23 },
  { id: 19, droneType: droneTypesMock[2], heading: 54, velocity: 26 },
  { id: 20, droneType: droneTypesMock[3], heading: 77, velocity: 29 },
  { id: 21, droneType: droneTypesMock[0], heading: 100, velocity: 32 },
  { id: 22, droneType: droneTypesMock[1], heading: 123, velocity: 35 },
  { id: 23, droneType: droneTypesMock[2], heading: 146, velocity: 38 },
  { id: 24, droneType: droneTypesMock[3], heading: 169, velocity: 41 },
  { id: 25, droneType: droneTypesMock[0], heading: 192, velocity: 20 },
  { id: 26, droneType: droneTypesMock[1], heading: 215, velocity: 23 },
  { id: 27, droneType: droneTypesMock[2], heading: 238, velocity: 26 },
  { id: 28, droneType: droneTypesMock[3], heading: 261, velocity: 29 },
  { id: 29, droneType: droneTypesMock[0], heading: 284, velocity: 32 },
  { id: 30, droneType: droneTypesMock[1], heading: 307, velocity: 35 },
  { id: 31, droneType: droneTypesMock[2], heading: 330, velocity: 38 },
  { id: 32, droneType: droneTypesMock[3], heading: 353, velocity: 41 },
  { id: 33, droneType: droneTypesMock[0], heading: 16, velocity: 20 },
  { id: 34, droneType: droneTypesMock[1], heading: 39, velocity: 23 },
  { id: 35, droneType: droneTypesMock[2], heading: 62, velocity: 26 },
  { id: 36, droneType: droneTypesMock[3], heading: 85, velocity: 29 },
  { id: 37, droneType: droneTypesMock[0], heading: 108, velocity: 32 },
  { id: 38, droneType: droneTypesMock[1], heading: 131, velocity: 35 },
  { id: 39, droneType: droneTypesMock[2], heading: 154, velocity: 38 },
  { id: 40, droneType: droneTypesMock[3], heading: 177, velocity: 41 },
];

export interface DroneEvent {
  id: string;

  drone: Drone;

  /** The ERD has no per-unit interceptor table; this is the interceptor model that responded */
  interceptor: InterceptorType;

  launcher: Launcher;

  /** Unix timestamp (seconds since epoch) */
  occurredAt: number;

  eventLocationType: EventLocationType;
  sector: Sector;
  launchingOrganization: LaunchingOrganization;

  /** Estimated damage caused by the drone, in ILS */
  damageCostIls: number;

  /** Number of casualties; 0 when none (internally estimated, not sourced) */
  casualtyCount: number;

  status: EventStatus;
}

export const droneEventsMock: DroneEvent[] = [
  {
    id: "2db92eff-f157-4c4d-8d9e-61fcd8641f06",
    drone: dronesMock[0],
    interceptor: interceptorTypesMock[0],
    launcher: launchersMock[0],
    occurredAt: 1788360219,
    eventLocationType: EventLocationType.INTERCEPT,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.INTERCEPTED,
  },
  {
    id: "97405991-a62f-4f41-a58b-8ee44e7493a1",
    drone: dronesMock[1],
    interceptor: interceptorTypesMock[1],
    launcher: launchersMock[3],
    occurredAt: 1788375699,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 9000,
    casualtyCount: 0,
    status: EventStatus.FELL_IN_OPEN_FIELD,
  },
  {
    id: "479f3bc5-2cd1-426d-bcf9-0a49961a1132",
    drone: dronesMock[2],
    interceptor: interceptorTypesMock[2],
    launcher: launchersMock[1],
    occurredAt: 1788390519,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 210000,
    casualtyCount: 1,
    status: EventStatus.HIT_TARGET,
  },
  {
    id: "3da547ff-6ab3-4326-99ad-5c2416245517",
    drone: dronesMock[3],
    interceptor: interceptorTypesMock[3],
    launcher: launchersMock[4],
    occurredAt: 1788405339,
    eventLocationType: EventLocationType.INTERCEPT,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.INTERCEPTED,
  },
  {
    id: "b73190b1-d8c4-4788-a811-1cee43c7c34a",
    drone: dronesMock[4],
    interceptor: interceptorTypesMock[4],
    launcher: launchersMock[2],
    occurredAt: 1788420159,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.IN_AIR,
  },
  {
    id: "e9a68f6f-66ba-449f-ba91-7583bacfa6bd",
    drone: dronesMock[5],
    interceptor: interceptorTypesMock[0],
    launcher: launchersMock[3],
    occurredAt: 1788436239,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 480000,
    casualtyCount: 1,
    status: EventStatus.HIT_TARGET,
  },
  {
    id: "bd1bc26f-fd5c-442f-b9a2-2e343967d960",
    drone: dronesMock[6],
    interceptor: interceptorTypesMock[1],
    launcher: launchersMock[0],
    occurredAt: 1788451059,
    eventLocationType: EventLocationType.INTERCEPT,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.INTERCEPTED,
  },
  {
    id: "c37417b6-e583-4855-b923-52fec82dccd5",
    drone: dronesMock[7],
    interceptor: interceptorTypesMock[2],
    launcher: launchersMock[4],
    occurredAt: 1788465879,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.IN_AIR,
  },
  {
    id: "e1c2b7c4-c323-434f-a0ef-6c979695c6f8",
    drone: dronesMock[8],
    interceptor: interceptorTypesMock[3],
    launcher: launchersMock[1],
    occurredAt: 1788480699,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 6000,
    casualtyCount: 0,
    status: EventStatus.FELL_IN_OPEN_FIELD,
  },
  {
    id: "4551154a-d746-42b5-b4b3-7cafa0749cbd",
    drone: dronesMock[9],
    interceptor: interceptorTypesMock[4],
    launcher: launchersMock[3],
    occurredAt: 1788496779,
    eventLocationType: EventLocationType.INTERCEPT,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.INTERCEPTED,
  },
  {
    id: "f00c5117-4092-417f-8106-64e11155cb89",
    drone: dronesMock[10],
    interceptor: interceptorTypesMock[0],
    launcher: launchersMock[2],
    occurredAt: 1788511599,
    eventLocationType: EventLocationType.INTERCEPT,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.INTERCEPTED,
  },
  {
    id: "f36f4424-251b-439d-9665-a38a695c94e1",
    drone: dronesMock[11],
    interceptor: interceptorTypesMock[1],
    launcher: launchersMock[4],
    occurredAt: 1788526419,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 10080,
    casualtyCount: 0,
    status: EventStatus.FELL_IN_OPEN_FIELD,
  },
  {
    id: "c8b95acc-9e1d-4320-a777-bd1d30f08b18",
    drone: dronesMock[12],
    interceptor: interceptorTypesMock[2],
    launcher: launchersMock[0],
    occurredAt: 1788541239,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 235200,
    casualtyCount: 2,
    status: EventStatus.HIT_TARGET,
  },
  {
    id: "fa08f32a-35d0-41af-86bc-597d1ec15a44",
    drone: dronesMock[13],
    interceptor: interceptorTypesMock[3],
    launcher: launchersMock[3],
    occurredAt: 1788557319,
    eventLocationType: EventLocationType.INTERCEPT,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.INTERCEPTED,
  },
  {
    id: "869fc0c3-6632-4e7a-bd10-6dceeef00066",
    drone: dronesMock[14],
    interceptor: interceptorTypesMock[4],
    launcher: launchersMock[1],
    occurredAt: 1788572139,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.IN_AIR,
  },
  {
    id: "adf123cf-29a8-43f7-a320-a47e65d1a572",
    drone: dronesMock[15],
    interceptor: interceptorTypesMock[0],
    launcher: launchersMock[4],
    occurredAt: 1788586959,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 537600,
    casualtyCount: 2,
    status: EventStatus.HIT_TARGET,
  },
  {
    id: "f79004f8-14e0-40c7-a50e-8db5123ae7f0",
    drone: dronesMock[16],
    interceptor: interceptorTypesMock[1],
    launcher: launchersMock[2],
    occurredAt: 1788601779,
    eventLocationType: EventLocationType.INTERCEPT,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.INTERCEPTED,
  },
  {
    id: "cbc41177-ff55-47c2-9dce-e20e91967eac",
    drone: dronesMock[17],
    interceptor: interceptorTypesMock[2],
    launcher: launchersMock[3],
    occurredAt: 1788617859,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.IN_AIR,
  },
  {
    id: "20ad0387-c977-4143-bf11-e46d4859b60b",
    drone: dronesMock[18],
    interceptor: interceptorTypesMock[3],
    launcher: launchersMock[0],
    occurredAt: 1788632679,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 6720,
    casualtyCount: 0,
    status: EventStatus.FELL_IN_OPEN_FIELD,
  },
  {
    id: "794466bc-a281-40d4-8847-622d6704409c",
    drone: dronesMock[19],
    interceptor: interceptorTypesMock[4],
    launcher: launchersMock[4],
    occurredAt: 1788647499,
    eventLocationType: EventLocationType.INTERCEPT,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.INTERCEPTED,
  },
  {
    id: "af046ed3-f471-4ba4-b589-38666fd870ef",
    drone: dronesMock[20],
    interceptor: interceptorTypesMock[0],
    launcher: launchersMock[1],
    occurredAt: 1788662319,
    eventLocationType: EventLocationType.INTERCEPT,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.INTERCEPTED,
  },
  {
    id: "42384d0c-7617-4b12-82a0-7956930bcfb4",
    drone: dronesMock[21],
    interceptor: interceptorTypesMock[1],
    launcher: launchersMock[3],
    occurredAt: 1788677139,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 11160,
    casualtyCount: 0,
    status: EventStatus.FELL_IN_OPEN_FIELD,
  },
  {
    id: "a74bc249-507d-4ff4-9dfc-15e4206df2b5",
    drone: dronesMock[22],
    interceptor: interceptorTypesMock[2],
    launcher: launchersMock[2],
    occurredAt: 1788693219,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 260400,
    casualtyCount: 1,
    status: EventStatus.HIT_TARGET,
  },
  {
    id: "e03f3a68-e592-4616-b566-8e012c70c995",
    drone: dronesMock[23],
    interceptor: interceptorTypesMock[3],
    launcher: launchersMock[4],
    occurredAt: 1788708039,
    eventLocationType: EventLocationType.INTERCEPT,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.INTERCEPTED,
  },
  {
    id: "8fb487b0-6c24-4397-8fd0-a89c0d674fab",
    drone: dronesMock[24],
    interceptor: interceptorTypesMock[4],
    launcher: launchersMock[0],
    occurredAt: 1788722859,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.IN_AIR,
  },
  {
    id: "faf400c1-ba70-4a3a-a0fc-537f9c229d04",
    drone: dronesMock[25],
    interceptor: interceptorTypesMock[0],
    launcher: launchersMock[3],
    occurredAt: 1788737679,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 595200,
    casualtyCount: 1,
    status: EventStatus.HIT_TARGET,
  },
  {
    id: "6d93e3ea-4097-4fb8-8c29-68f9d6ce2021",
    drone: dronesMock[26],
    interceptor: interceptorTypesMock[1],
    launcher: launchersMock[1],
    occurredAt: 1788753759,
    eventLocationType: EventLocationType.INTERCEPT,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.INTERCEPTED,
  },
  {
    id: "7bfc15a3-2d24-4a95-959d-481d6e17a277",
    drone: dronesMock[27],
    interceptor: interceptorTypesMock[2],
    launcher: launchersMock[4],
    occurredAt: 1788768579,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.IN_AIR,
  },
  {
    id: "836104f3-e577-4b28-871e-67be7d0f2a7b",
    drone: dronesMock[28],
    interceptor: interceptorTypesMock[3],
    launcher: launchersMock[2],
    occurredAt: 1788783399,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 7440,
    casualtyCount: 0,
    status: EventStatus.FELL_IN_OPEN_FIELD,
  },
  {
    id: "76cf928f-af1c-4cd1-8284-08b94f355b1a",
    drone: dronesMock[29],
    interceptor: interceptorTypesMock[4],
    launcher: launchersMock[3],
    occurredAt: 1788798219,
    eventLocationType: EventLocationType.INTERCEPT,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.INTERCEPTED,
  },
  {
    id: "9732a859-8640-4e3f-8ea9-d7374888a3f4",
    drone: dronesMock[30],
    interceptor: interceptorTypesMock[0],
    launcher: launchersMock[0],
    occurredAt: 1788814299,
    eventLocationType: EventLocationType.INTERCEPT,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.INTERCEPTED,
  },
  {
    id: "fc213b72-71e1-4e4c-85c9-993d02b7b0bc",
    drone: dronesMock[31],
    interceptor: interceptorTypesMock[1],
    launcher: launchersMock[4],
    occurredAt: 1788829119,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 12240,
    casualtyCount: 0,
    status: EventStatus.FELL_IN_OPEN_FIELD,
  },
  {
    id: "5f2d4f39-4043-45db-a6b4-d3d45cb0b207",
    drone: dronesMock[32],
    interceptor: interceptorTypesMock[2],
    launcher: launchersMock[1],
    occurredAt: 1788843939,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 285600,
    casualtyCount: 2,
    status: EventStatus.HIT_TARGET,
  },
  {
    id: "b83f51ef-a966-43b7-ae74-8dcc9dc14283",
    drone: dronesMock[33],
    interceptor: interceptorTypesMock[3],
    launcher: launchersMock[3],
    occurredAt: 1788858759,
    eventLocationType: EventLocationType.INTERCEPT,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.INTERCEPTED,
  },
  {
    id: "deae7324-c6ca-4e49-a1d6-2570fb7a8da6",
    drone: dronesMock[34],
    interceptor: interceptorTypesMock[4],
    launcher: launchersMock[2],
    occurredAt: 1788874839,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.IN_AIR,
  },
  {
    id: "b5907b7f-47a9-4482-8d9e-9414a9199c76",
    drone: dronesMock[35],
    interceptor: interceptorTypesMock[0],
    launcher: launchersMock[4],
    occurredAt: 1788889659,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 652800,
    casualtyCount: 2,
    status: EventStatus.HIT_TARGET,
  },
  {
    id: "41ff32bd-0eab-4b08-8840-98435e2ad703",
    drone: dronesMock[36],
    interceptor: interceptorTypesMock[1],
    launcher: launchersMock[0],
    occurredAt: 1788904479,
    eventLocationType: EventLocationType.INTERCEPT,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.INTERCEPTED,
  },
  {
    id: "f674aa18-26ce-48be-b8e2-bfdbf9013e67",
    drone: dronesMock[37],
    interceptor: interceptorTypesMock[2],
    launcher: launchersMock[3],
    occurredAt: 1788919299,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.IN_AIR,
  },
  {
    id: "48357808-f7f2-4d47-be5d-9489b584975d",
    drone: dronesMock[38],
    interceptor: interceptorTypesMock[3],
    launcher: launchersMock[1],
    occurredAt: 1788935379,
    eventLocationType: EventLocationType.FALL,
    sector: Sector.GAZA,
    launchingOrganization: LaunchingOrganization.HAMAS,
    damageCostIls: 8160,
    casualtyCount: 0,
    status: EventStatus.FELL_IN_OPEN_FIELD,
  },
  {
    id: "cfd09d89-8a09-4f0b-9b62-a53c20435171",
    drone: dronesMock[39],
    interceptor: interceptorTypesMock[4],
    launcher: launchersMock[4],
    occurredAt: 1788950199,
    eventLocationType: EventLocationType.INTERCEPT,
    sector: Sector.LEBANON,
    launchingOrganization: LaunchingOrganization.HEZBOLLAH,
    damageCostIls: 0,
    casualtyCount: 0,
    status: EventStatus.INTERCEPTED,
  },
];
