name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
      

# jobs:
#   trigger:
#     runs-on: self-hosted

#     steps:
#       - name: Trigger Pipeline
#         run: |
#           echo $GH_TOKEN
#           gh workflow run main.yml \
#             --repo Amit11234/until-midnight-infra \
#             --ref main 
#         env:
#           GH_TOKEN: ${{ secrets.INFRA_TOKEN }}

jobs:
  pipeline:
    uses: Devops-Had-Hatzot/ci-template/.github/workflows/main.yml@main
