name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps: 
      - name: Trigger Pipeline
        run: |
          gh workflow run main.yml \
            --repo Amit11234/until-midnight-infra \
            -- ref main \
            -f environment=dev
        env:
          GH_TOKEN: ${{ secrets.INFRA_TOKEN }}
          
